

# CAN IDs
[can_ids]
#----------- Sensor Hub -----------
# ///  Pod Drop Switches  ///
#[sensor_hub]
DROP1 = 136
DROP2 = 137
DROP3 = 141
DROP4 = 105
DROP5 = 109
DROP6 = 107
DROP7 = 127
DROP8 = 104
DROP9 = 126
DROP10 = 127
DROP11 = 114
DROP12 = 125
DROP13 = 111
DROP14 = 112
DROP15 = 110
DROP16 = 124
EOT = 133
MCU_REARM = 108
MCU_BRAKE = 106
DRIVES = 138
EME = 135

#^^^^^^^^^^^^^^^^^^^^^^^^^^^
# If any of the values above is read as ID it means that the message buffer is empty and the pob had to brake for some reason.
# Meaning that we will transition directly to the Emergency Braking state or the exit state.
# The only ones im not so sure about are the MCU_REARM and MCU_BRAKE. Im not sure if they are pod drop switches or not or are simply the response to the requested action from the MCU.
#^^^^^^^^^^^^^^^^^^^^^^^^^^^


#///   Pressure Sensors  ///
#[pressure]
HIGH_PRESSURE_SENSOR = 140
LOW_PRESSURE_SENSOR = 139

#//   IMU    //
#/\ Accelerometer /\
#[accelerometer]
ACCX = 121
ACCY = 120
ACCZ = 119

#/\ Gyroscope /\
#[gyroscope]
GYRX = 118
GYRY = 117
GYRZ = 116

#/\ Temperature /\
#[temperature]
TEMP = 115

#^^^^^^^^^^^^^^^^^^^^^^^^^^
#All the above need to have some kind of threshold to determine if the pod is in a safe state or not.
#If so they will either trigger the Brakes or we will simply send this values to the ground station and it will send us back an emergency code or not.
#This is still to be decided but we are sure they have to go to the ground station.
#^^^^^^^^^^^^^^^^^^^^^^^^^^


#-------- This was all for the sensor hub --------

