[[Command]]
name = "DefaultCommand"
id = 0x01

[[Command]]
name = "Heartbeat"
id = 0x042

[[Command]]
name = "ls0"
id = 0x400

[[Command]]
name = "ls1"
id = 0x401

[[Command]]
name = "ls2"
id = 0x402

[[Command]]
name = "enable_axis"
id = 0x403

[[Command]]
name = "disable_axis"
id = 0x404

[[Command]]
name = "init"
id = 0x405

[[Command]]
name = "reboot"
id = 0x406

[[Command]]
name = "launch"
id = 0x407

[[Command]]
name = "vert0"
id = 0x408

[[Command]]
name = "lat0"
id = 0x409

[[Command]]
name = "land"
id = 0x410

[[Command]]
name = "vert_mode_normal"
id = 0x412

[[Command]]
name = "lat_mode_normal"
id = 0x413

[[Command]]
name = "vert_mode_offsets"
id = 0x414

[[Command]]
name = "vert_mode_dance"
id = 0x415

[[Command]]
name = "vert_mode_sine"
id = 0x416

[[Command]]
name = "vert0_reset"
id = 0x417

[[Command]]
name = "lat0_reset"
id = 0x418

[[Command]]
name = "SetRoute"
id = 0x5c

[[Command]]
name = "SetSpeeds"
id = 0x59

[[Command]]
name = "StartRun"
id = 0x5d

[[Command]]
name = "EmergencyBrake"
id = 0xff

[[Command]]
name = "Shutdown"
id = 0x5f

[[Command]]
name = "StartHV"
id = 0x60

[[Command]]
name = "StopHV"
id = 0x61

[[Command]]
name = "OpenContactor"
id = 0x62

[[Command]]
name = "CloseContactor"
id = 0x63

[[Command]]
name = "DcOff"
id = 0x64

[[Command]]
name = "DcOn"
id = 0x65

[[Command]]
name = "SystemReset"
id = 0x66

[[Command]]
name = "ArmBrakes"
id = 0x69

[[Command]]
name = "FinishRunConfig"
id = 0x67

[[Command]]
name = "LeviPropulsionStart"
id = 0x68

[[Command]]
name = "LeviPropulsionStop"
id = 0x70 

#[[Command]]
#name = "TurnAllHVRelaysOnUNSAFE"
#id = 0x68

[[Command]]
name = "EmitEvent"
id = 0x7A0
