[[Command]]
name = "DefaultCommand"
id = 0x01

[[Command]]
name = "Levitate"
id = 0x5a

[[Command]]
name = "StopLevitating"
id = 0x5b

[[Command]]
name = "Configure"
id = 0x5c

[[Command]]
name = "StartRun"
id = 0x5d

[[Command]]
name = "EmergencyBrake"
id = 0xff

[[Command]]
name = "Shutdown"
id = 0x5f

[[Command]]
name = "StartHV"
id = 0x60

[[Command]]
name = "StopHV"
id = 0x61

[[Command]]
name = "OpenContactor"
id = 0x62

[[Command]]
name = "CloseContactor"
id = 0x63

[[Command]]
name = "DcOff"
id = 0x63

[[Command]]
name = "DcOn"
id = 0x64

[[Command]]
name = "EmitEvent"
id = 0x7A0
