[gs]
ip = [192, 168, 1, 4]
port = 6942
udp_port = 6943
buffer_size = 1460 # this is the MAXIMUM size of messages transmitted, in bytes.
timeout = 15000 # this is the timeout for the socket, in milliseconds.
status_channel = "status_channel"
info_channel = "info_channel"
warning_channel = "warning_channel"
error_channel = "error_channel"
levi_exec_path = "C:/Rust/Helios_III/gs/station/Levi/windows-x86_64-debug/PmpGettingStartedCs.exe"

[pod.net]
ip = [192, 168, 1, 69]
port = 17034
udp_port = 17035
mac_addr = [0x00, 0x1e, 0x67, 0x4c, 0x5c, 0x3e]
keep_alive = 1000 # keep alive interval, in milliseconds.

[pod.internal]
event_queue_size = 128
data_queue_size = 256
can_queue_size = 128

[pod.bms]
lv_ids = [0x19C, 0x19D, 0x19E, 0x19F, 0x1A0, 0x1A1, 0x1A2, 0x1A3, 0x1A4, 0x1A5, 0x1A6, 0x1BC, 0x1DC, 0x1FC, 0x29C,0x221]
hv_ids = [0x3A0, 0x3A1, 0x3A2, 0x3A3, 0x3A4, 0x3A5, 0x3A6, 0x3A7, 0x3A8, 0x3A9, 0x3AA, 0x3C0, 0x3E0, 0x400, 0x4A0, 0x425]
gfd_ids = [0x37,0x38,0x39]
sensor_hub = [0x1b,0x1c,0x1d,0x15]


