## -
[[Datatype]]
name = "DefaultDatatype"
id = 0x00

[[Datatype]]
name = "PropulsionVoltage"
id = 0x1b2

[[Datatype]]
name = "PropulsionCurrent"
id = 0x1b3

[[Datatype]]
name = "PropulsionVRefInt"
id = 0x1b4

[[Datatype]]
name = "LevitationTemperature"
id = 0x0b

[[Datatype]]
name = "AccelerationX"
id = 0x115

[[Datatype]]
name = "AccelerationY"
id = 0x114

[[Datatype]]
name = "AccelerationZ"
id = 0x113

[[Datatype]]
name = "GyroscopeX"
id = 0x112

[[Datatype]]
name = "GyroscopeY"
id = 0x111

[[Datatype]]
name = "GyroscopeZ"
id = 0x110

[[Datatype]]
name = "IMDGeneralInfo"
id = 0x37

[[Datatype]]
name = "IMDIsolationDetails"
id = 0x38

[[Datatype]]
name = "IMDVoltageDetails"
id = 0x39


[[Datatype]]
name = "InsulationNegative"
id = 0x50A

[[Datatype]]
name = "InsulationPositive"
id = 0x50B

[[Datatype]]
name = "InsulationOriginal"
id = 0x50C

[[Datatype]]
name = "DefaultBMSLow"
id = 0x19C
[[Datatype]]
name = "DiagnosticBMSLow"
id = 0x1A3
[[Datatype]]
name = "DefaultBMSHigh"
id = 0x3A0
[[Datatype]]
name = "DiagnosticBMSHigh"
id = 0x3A7

[[Datatype]]
name = "BatteryVoltageLow"
id = 0x19D
[[Datatype]]
name = "BatteryVoltageHigh"
id = 0x3A1

[[Datatype]]
name = "TotalBatteryVoltageLow"
id = 0x1A5

[[Datatype]]
name = "TotalBatteryVoltageHigh"
id = 0x3A9


[[Datatype]]
name = "BatteryTemperatureLow"
id = 0x1A4
[[Datatype]]
name = "BatteryTemperatureHigh"
id = 0x3A8

[[Datatype]]
name = "BatteryBalanceLow"
id = 0x19F

[[Datatype]]
name = "BatteryBalanceHigh"
id = 0x3A3

[[Datatype]]
name = "SingleCellVoltageLow"
id = 0x1BC

[[Datatype]]
name = "SingleCellTemperatureLow"
id = 0x1DC

[[Datatype]]
name = "ChargeStateLow"
id = 0x1A1

[[Datatype]]
name = "ChargeStateHigh"
id = 0x3A5

[[Datatype]]
name = "BatteryCurrentLow"
id = 0x1A6

[[Datatype]]
name = "BatteryCurrentHigh"
id = 0x3AA

[[Datatype]]
name = "BatteryEnergyParamsLow"
id = 0x1A2

[[Datatype]]
name = "BatteryEnergyParamsHigh"
id = 0x3A6

[[Datatype]]
name = "BatteryMaxVoltageLow"
id = 0x1A8

[[Datatype]]
name = "BatteryEstimatedChargeLow"
id = 0x1A9

[[Datatype]]
name = "BatteryMinTemperatureLow"
id = 0x1AA

[[Datatype]]
name = "BatteryMaxTemperatureLow"
id = 0x1AB

[[Datatype]]
name = "BatteryMinBalancingLow"
id = 0x1AC

[[Datatype]]
name = "BatteryMaxBalancingLow"
id = 0x1AD

[[Datatype]]
name = "BatteryMinVoltageLow"
id = 0x1A7

[[Datatype]]
name = "BatteryMinVoltageHigh"
id = 0x3AB

[[Datatype]]
name = "BatteryMaxVoltageHigh"
id = 0x3AC

[[Datatype]]
name = "BatteryEstimatedChargeHigh"
id = 0x3AD

[[Datatype]]
name = "BatteryMinTemperatureHigh"
id = 0x3AE

[[Datatype]]
name = "BatteryMaxTemperatureHigh"
id = 0x3AF

[[Datatype]]
name = "BatteryMinBalancingHigh"
id = 0x3B0


[[Datatype]]
name = "BatteryMaxBalancingHigh"
id = 0x3B1

[[Datatype]]
name = "BatteryEventLow"
id = 0x221

[[Datatype]]
name = "BatteryEventHigh"
id = 0x425

[[Datatype]]
name = "BrakeTemperature"
id = 0x13

[[Datatype]]
name = "PropulsionSpeed"
id = 0x14


[[Datatype]]
name = "FSMState"
id = 0x18

[[Datatype]]
name = "FSMEvent"
id = 0x19

[[Datatype]]
name = "EndOfTrackTriggered"
id = 0x1a

[[Datatype]]
name = "Localisation"
id = 0x500

[[Datatype]]
name = "Velocity"
id = 0x501

[[Datatype]]
name = "Acceleration"
id = 0x506

[[Datatype]]
name = "Direction"
id = 0x1d

[[Datatype]]
name = "BrakePressure"
id = 0x15

[[Datatype]]
name = "UnknownCanId"
id = 0x7F0

[[Datatype]]
name = "Info"
id = 0x7FA


[[Datatype]]
name = "Presure_VB"
id = 0x210

[[Datatype]]
name = "Average_Temp_VB_Bottom"
id = 0x211


[[Datatype]]
name = "Average_Temp_VB_top"
id = 0x200



[[Datatype]]
name = "Temp_HEMS_1"
id = 0x20a

[[Datatype]]
name = "Temp_HEMS_2"
id = 0x20b

[[Datatype]]
name = "Temp_HEMS_3"
id = 0x20c

[[Datatype]]
name = "Temp_HEMS_4"
id = 0x20d


[[Datatype]]
name = "Temp_Motor_1"
id = 0x20e

[[Datatype]]
name = "Temp_Motor_2"
id = 0x20f

[[Datatype]]
name = "Ambient_presure"
id = 0x220

[[Datatype]]
name = "Ambient_temp"
id = 0x224

[[Datatype]]
name = "Temp_EMS_1"
id = 0x222

[[Datatype]]
name = "Temp_EMS_2"
id = 0x223



[[Datatype]]
name = "SingleCellVoltageHigh_1"
id = 0x3C0

[[Datatype]]
name = "SingleCellTemperatureHigh_1"
id = 0x4A0

[[Datatype]]
name = "SingleCellVoltageHigh_2"
id = 0x3C1

[[Datatype]]
name = "SingleCellTemperatureHigh_2"
id = 0x4A1

[[Datatype]]
name = "SingleCellVoltageHigh_3"
id = 0x3C2

[[Datatype]]
name = "SingleCellTemperatureHigh_3"
id = 0x4A2

[[Datatype]]
name = "SingleCellVoltageHigh_4"
id = 0x3C3

[[Datatype]]
name = "SingleCellTemperatureHigh_4"
id = 0x4A3

[[Datatype]]
name = "SingleCellVoltageHigh_5"
id = 0x3C4

[[Datatype]]
name = "SingleCellTemperatureHigh_5"
id = 0x4A4

[[Datatype]]
name = "SingleCellVoltageHigh_6"
id = 0x3C5

[[Datatype]]
name = "SingleCellTemperatureHigh_6"
id = 0x4A5

[[Datatype]]
name = "SingleCellVoltageHigh_7"
id = 0x3C6

[[Datatype]]
name = "SingleCellTemperatureHigh_7"
id = 0x4A6

[[Datatype]]
name = "SingleCellVoltageHigh_8"
id = 0x3C7

[[Datatype]]
name = "SingleCellTemperatureHigh_8"
id = 0x4A7

[[Datatype]]
name = "SingleCellVoltageHigh_9"
id = 0x3C8

[[Datatype]]
name = "SingleCellTemperatureHigh_9"
id = 0x4A8

[[Datatype]]
name = "SingleCellVoltageHigh_10"
id = 0x3C9

[[Datatype]]
name = "SingleCellTemperatureHigh_10"
id = 0x4A9

[[Datatype]]
name = "SingleCellVoltageHigh_11"
id = 0x3CA

[[Datatype]]
name = "SingleCellTemperatureHigh_11"
id = 0x4AA

[[Datatype]]
name = "SingleCellVoltageHigh_12"
id = 0x3CB

[[Datatype]]
name = "SingleCellTemperatureHigh_12"
id = 0x4AB

[[Datatype]]
name = "SingleCellVoltageHigh_13"
id = 0x3CC

[[Datatype]]
name = "SingleCellTemperatureHigh_13"
id = 0x4AC

[[Datatype]]
name = "SingleCellVoltageHigh_14"
id = 0x3CD

[[Datatype]]
name = "SingleCellTemperatureHigh_14"
id = 0x4AD

[[Datatype]]
name = "Module1MaxVoltage"
id = 0x4B0

[[Datatype]]
name = "Module2MaxVoltage"
id = 0x4B1

[[Datatype]]
name = "Module3MaxVoltage"
id = 0x4B2

[[Datatype]]
name = "Module4MaxVoltage"
id = 0x4B3

[[Datatype]]
name = "Module5MaxVoltage"
id = 0x4B4

[[Datatype]]
name = "Module6MaxVoltage"
id = 0x4B5

[[Datatype]]
name = "Module7MaxVoltage"
id = 0x4B6

[[Datatype]]
name = "Module8MaxVoltage"
id = 0x4B7

[[Datatype]]
name = "Module1MinVoltage"
id = 0x4B8

[[Datatype]]
name = "Module2MinVoltage"
id = 0x4B9

[[Datatype]]
name = "Module3MinVoltage"
id = 0x4BA

[[Datatype]]
name = "Module4MinVoltage"
id = 0x4BB

[[Datatype]]
name = "Module5MinVoltage"
id = 0x4BC

[[Datatype]]
name = "Module6MinVoltage"
id = 0x4BD

[[Datatype]]
name = "Module7MinVoltage"
id = 0x4BE

[[Datatype]]
name = "Module8MinVoltage"
id = 0x4BF

[[Datatype]]
name = "Module1MaxTemperature"
id = 0x4C0

[[Datatype]]
name = "Module2MaxTemperature"
id = 0x4C1

[[Datatype]]
name = "Module3MaxTemperature"
id = 0x4C2

[[Datatype]]
name = "Module4MaxTemperature"
id = 0x4C3

[[Datatype]]
name = "Module5MaxTemperature"
id = 0x4C4

[[Datatype]]
name = "Module6MaxTemperature"
id = 0x4C5

[[Datatype]]
name = "Module7MaxTemperature"
id = 0x4C6

[[Datatype]]
name = "Module8MaxTemperature"
id = 0x4C7

[[Datatype]]
name = "Module1MinTemperature"
id = 0x4C8

[[Datatype]]
name = "Module2MinTemperature"
id = 0x4C9

[[Datatype]]
name = "Module3MinTemperature"
id = 0x4CA

[[Datatype]]
name = "Module4MinTemperature"
id = 0x4CB

[[Datatype]]
name = "Module5MinTemperature"
id = 0x4CC

[[Datatype]]
name = "Module6MinTemperature"
id = 0x4CD

[[Datatype]]
name = "Module7MinTemperature"
id = 0x4CE

[[Datatype]]
name = "Module8MinTemperature"
id = 0x4CF

[[Datatype]]
name = "Module1AvgVoltage"
id = 0x4D0

[[Datatype]]
name = "Module2AvgVoltage"
id = 0x4D1

[[Datatype]]
name = "Module3AvgVoltage"
id = 0x4D2

[[Datatype]]
name = "Module4AvgVoltage"
id = 0x4D3

[[Datatype]]
name = "Module5AvgVoltage"
id = 0x4D4

[[Datatype]]
name = "Module6AvgVoltage"
id = 0x4D5

[[Datatype]]
name = "Module7AvgVoltage"
id = 0x4D6

[[Datatype]]
name = "Module8AvgVoltage"
id = 0x4D7

[[Datatype]]
name = "Module1AvgTemperature"
id = 0x4D8

[[Datatype]]
name = "Module2AvgTemperature"
id = 0x4D9

[[Datatype]]
name = "Module3AvgTemperature"
id = 0x4DA

[[Datatype]]
name = "Module4AvgTemperature"
id = 0x4DB

[[Datatype]]
name = "Module5AvgTemperature"
id = 0x4DC

[[Datatype]]
name = "Module6AvgTemperature"
id = 0x4DD

[[Datatype]]
name = "Module7AvgTemperature"
id = 0x4DE

[[Datatype]]
name = "Module8AvgTemperature"
id = 0x4DF

[[Datatype]]
name = "ResponseHeartbeat"
id = 0x678

[[Datatype]]
name = "LeviInstruction"
id = 0x777

[[Datatype]]
name = "LowPressureSensor"
id = 0x127

[[Datatype]]
name = "HighPressureSensor"
id = 0x128


# SJOERD LEVITATION DATATYPES

[[Datatype]]
name = "levi_hems_gap_a"
id = 0x130

[[Datatype]]
name = "levi_hems_gap_b"
id = 0x131

[[Datatype]]
name = "levi_hems_gap_c"
id = 0x132

[[Datatype]]
name = "levi_hems_gap_d"
id = 0x133

[[Datatype]]
name = "levi_ems_gap_a"
id = 0x134

[[Datatype]]
name = "levi_ems_gap_b"
id = 0x135

[[Datatype]]
name = "levi_ems_gap_c"
id = 0x136

[[Datatype]]
name = "levi_ems_gap_d"
id = 0x137

[[Datatype]]
name = "levi_hems_current_a1"
id = 0x138

[[Datatype]]
name = "levi_hems_current_a2"
id = 0x139

[[Datatype]]
name = "levi_hems_current_b1"
id = 0x140

[[Datatype]]
name = "levi_hems_current_b2"
id = 0x141

[[Datatype]]
name = "levi_hems_current_c1"
id = 0x142

[[Datatype]]
name = "levi_hems_current_c2"
id = 0x143

[[Datatype]]
name = "levi_hems_current_d1"
id = 0x144

[[Datatype]]
name = "levi_hems_current_d2"
id = 0x145

[[Datatype]]
name = "levi_ems_current_ab"
id = 0x146

[[Datatype]]
name = "levi_ems_current_cd"
id = 0x147

[[Datatype]]
name = "levi_hems_airgap"
id = 0x148

[[Datatype]]
name = "levi_hems_pitch"
id = 0x149

[[Datatype]]
name = "levi_hems_roll"
id = 0x150

[[Datatype]]
name = "levi_ems_offset_ab"
id = 0x151

[[Datatype]]
name = "levi_ems_offset_cd"
id = 0x152

[[Datatype]]
name = "levi_hems_power"
id = 0x153

[[Datatype]]
name = "levi_ems_power"
id = 0x154

[[Datatype]]
name = "levi_volt_min"
id = 0x155

[[Datatype]]
name = "levi_volt_max"
id = 0x156

[[Datatype]]
name = "levi_volt_avg"
id = 0x157

