## -
[[Datatype]]
name = "DefaultDatatype"
id = 0x00

[[Datatype]]
name = "PropulsionTemperature"
id = 0x0a

[[Datatype]]
name = "LevitationTemperature"
id = 0x0b


[[Datatype]]
name = "IMDGeneralInfo"
id = 0x37

[[Datatype]]
name = "IMDIsolationDetails"
id = 0x38

[[Datatype]]
name = "IMDVoltageDetails"
id = 0x39


[[Datatype]]
name = "InsulationNegative"
id = 0x50A

[[Datatype]]
name = "InsulationPositive"
id = 0x50B

[[Datatype]]
name = "InsulationOriginal"
id = 0x50C

[[Datatype]]
name = "DefaultBMSLow"
id = 0x19C
[[Datatype]]
name = "DiagonosticBMSLow"
id = 0x1A3
[[Datatype]]
name = "DefaultBMSHigh"
id = 0x3A0
[[Datatype]]
name = "DiagonosticBMSHigh"
id = 0x3A7


[[Datatype]]
name = "BatteryVoltageLow"
id = 0x19D
[[Datatype]]
name = "BatteryVoltageHigh"
id = 0x3A1

[[Datatype]]
name = "TotalBatteryVoltageLow"
id = 0x1A5

[[Datatype]]
name = "TotalBatteryVoltageHigh"
id = 0x3A9


[[Datatype]]
name = "BatteryTemperatureLow"
id = 0x1A4
[[Datatype]]
name = "BatteryTemperatureHigh"
id = 0x3A8

[[Datatype]]
name = "BatteryBalanceLow"
id = 0x19F

[[Datatype]]
name = "BatteryBalanceHigh"
id = 0x3A3

[[Datatype]]
name = "SingleCellVoltageLow"
id = 0x1BC

[[Datatype]]
name = "SingleCellTemperatureLow"
id = 0x1DC

[[Datatype]]
name = "ChargeStateLow"
id = 0x1A1

[[Datatype]]
name = "SingleCellVoltageHigh"
id = 0x3C0

[[Datatype]]
name = "SingleCellTemperatureHigh"
id = 0x4A0

[[Datatype]]
name = "ChargeStateHigh"
id = 0x3A5

[[Datatype]]
name = "BatteryCurrentLow"
id = 0x1A6

[[Datatype]]
name = "BatteryCurrentHigh"
id = 0x3AA

[[Datatype]]
name = "BatteryEnergyParamsLow"
id = 0x1A2

[[Datatype]]
name = "BatteryEnergyParamsHigh"
id = 0x3A6

[[Datatype]]
name = "BatteryMaxVoltageLow"
id = 0x1A8

[[Datatype]]
name = "BatteryEstimatedChargeLow"
id = 0x1A9

[[Datatype]]
name = "BatteryMinTemperatureLow"
id = 0x1AA

[[Datatype]]
name = "BatteryMaxTemperatureLow"
id = 0x1AB

[[Datatype]]
name = "BatteryMinBalancingLow"
id = 0x1AC

[[Datatype]]
name = "BatteryMaxBalancingLow"
id = 0x1AD

[[Datatype]]
name = "BatteryMinVoltageLow"
id = 0x1A7

[[Datatype]]
name = "BatteryMinVoltageHigh"
id = 0x3AB

[[Datatype]]
name = "BatteryMaxVoltageHigh"
id = 0x3AC

[[Datatype]]
name = "BatteryEstimatedChargeHigh"
id = 0x3AD

[[Datatype]]
name = "BatteryMinTemperatureHigh"
id = 0x3AE

[[Datatype]]
name = "BatteryMaxTemperatureHigh"
id = 0x3AF

[[Datatype]]
name = "BatteryMinBalancingHigh"
id = 0x3B0


[[Datatype]]
name = "BatteryMaxBalancingHigh"
id = 0x3B1

[[Datatype]]
name = "BatteryEventLow"
id = 0x221

[[Datatype]]
name = "BatteryEventHigh"
id = 0x425

[[Datatype]]
name = "BrakeTemperature"
id = 0x13

[[Datatype]]
name = "PropulsionSpeed"
id = 0x14


[[Datatype]]
name = "FSMState"
id = 0x18

[[Datatype]]
name = "FSMEvent"
id = 0x19

[[Datatype]]
name = "EndOfTrackTriggered"
id = 0x1a

[[Datatype]]
name = "Localisation"
id = 0x1b

[[Datatype]]
name = "Velocity"
id = 0x1c

[[Datatype]]
name = "Direction"
id = 0x1d

[[Datatype]]
name = "BrakePressure"
id = 0x15

[[Datatype]]
name = "UnknownCanId"
id = 0x7F0
[[Datatype]]
name = "Info"
id = 0x7FA


[[Datatype]]
name = "TempPCB1"
id = 0x210

[[Datatype]]
name = "TempPCB2"
id = 0x211

[[Datatype]]
name = "TempPCB3"
id = 0x212

[[Datatype]]
name = "TempPCB4"
id = 0x213

[[Datatype]]
name = "TempPCB5"
id = 0x214

[[Datatype]]
name = "TempPCB6"
id = 0x215

[[Datatype]]
name = "TempPCB7"
id = 0x216

[[Datatype]]
name = "TempPCB8"
id = 0x217

[[Datatype]]
name = "TempPCB9"
id = 0x218

[[Datatype]]
name = "TempPCB10"
id = 0x219

[[Datatype]]
name = "TempPCB11"
id = 0x200

[[Datatype]]
name = "TempPCB12"
id = 0x201

[[Datatype]]
name = "TempPCB13"
id = 0x202

[[Datatype]]
name = "TempPCB14"
id = 0x203

[[Datatype]]
name = "TempPCB15"
id = 0x204

[[Datatype]]
name = "TempPCB16"
id = 0x205

[[Datatype]]
name = "TempPCB17"
id = 0x206

[[Datatype]]
name = "TempPCB18"
id = 0x207

[[Datatype]]
name = "TempPCB19"
id = 0x208

[[Datatype]]
name = "TempPCB20"
id = 0x209

[[Datatype]]
name = "TempPCB21"
id = 0x20a

[[Datatype]]
name = "TempPCB22"
id = 0x20b

[[Datatype]]
name = "TempPCB23"
id = 0x20c

[[Datatype]]
name = "TempPCB24"
id = 0x20d

[[Datatype]]
name = "TempPCB25"
id = 0x20e

[[Datatype]]
name = "TempPCB26"
id = 0x20f

[[Datatype]]
name = "TempPCB27"
id = 0x220

[[Datatype]]
name = "TempPCB28"
id = 0x224

[[Datatype]]
name = "TempPCB29"
id = 0x222

[[Datatype]]
name = "TempPCB30"
id = 0x223

[[Datatype]]
name = "location"
id = 0x500

[[Datatype]]
name = "velocity"
id = 0x501


