
[[Datatype]]
name = "DefaultDatatype"
id = 0x00

[[Datatype]]
name = "PropulsionTemperature"
id = 0x0a

[[Datatype]]
name = "LevitationTemperature"
id = 0x0b

[[Datatype]]
name = "BatteryVoltage"
id = 0x19D

[[Datatype]]
name = "TotalBatteryVoltage"
id = 0x1A2

[[Datatype]]
name = "BatteryTemperature"
id = 0x1A4

[[Datatype]]
name = "BatteryBalance"
id = 0x1A0

[[Datatype]]
name = "SingleCellVoltage"
id = 0x1BC

[[Datatype]]
name = "SingleCellTemperature"
id = 0x1DC

[[Datatype]]
name = "ChargeState"
id = 0x1A1

[[Datatype]]
name = "BatteryCurrent"
id = 0x1A3

[[Datatype]]
name = "BrakeTemperature"
id = 0x13

[[Datatype]]
name = "PropulsionSpeed"
id = 0x14

[[Datatype]]
name = "BrakePressure"
id = 0x15

[[Datatype]]
name = "HighVoltage"
id = 0x16

[[Datatype]]
name = "HighVoltageInsulation"
id = 0x17

[[Datatype]]
name = "FSMState"
id = 0x18

[[Datatype]]
name = "FSMEvent"
id = 0x19

[[Datatype]]
name = "PodDropTriggered"
id = 0x1a

[[Datatype]]
name = "Localisation"
id = 0x1b

[[Datatype]]
name = "GFDIsolation"
id = 0x38

[[Datatype]]
name = "DefaultBMS"
id = 0x19C

[[Datatype]]
name = "UnknownCanId"
id = 0x7F0

[[Datatype]]
name = "Info"
id = 0x7FA
