## Every time this file is changed, you also need to update:
## pod:
## - communication/mod.rs
## gs:
## - api/mod.rs
## -
[[Datatype]]
name = "DefaultDatatype"
id = 0x00

[[Datatype]]
name = "PropulsionTemperature"
id = 0x0a

[[Datatype]]
name = "LevitationTemperature"
id = 0x0b

[[Datatype]]
name = "BatteryVoltageLow"
id = 0x19D
[[Datatype]]
name = "BatteryVoltageHigh"
id = 0x400

[[Datatype]]
name = "TotalBatteryVoltageLow"
id = 0x1A2

[[Datatype]]
name = "TotalBatteryVoltageHigh"
id = 0x401


[[Datatype]]
name = "BatteryTemperatureLow"
id = 0x1A4
[[Datatype]]
name = "BatteryTemperatureHigh"
id = 0x402

[[Datatype]]
name = "BatteryBalanceLow"
id = 0x1A0

[[Datatype]]
name = "BatteryBalanceHigh"
id = 0x403

[[Datatype]]
name = "SingleCellVoltageLow"
id = 0x1BC

[[Datatype]]
name = "SingleCellTemperatureLow"
id = 0x1DC

[[Datatype]]
name = "ChargeStateLow"
id = 0x1A1

[[Datatype]]
name = "SingleCellVoltageHigh"
id = 0x405

[[Datatype]]
name = "SingleCellTemperatureHigh"
id = 0x406

[[Datatype]]
name = "ChargeStateHigh"
id = 0x407

[[Datatype]]
name = "BatteryCurrentLow"
id = 0x1A3

[[Datatype]]
name = "BatteryCurrentHigh"
id = 0x404

[[Datatype]]
name = "BrakeTemperature"
id = 0x13

[[Datatype]]
name = "PropulsionSpeed"
id = 0x14

[[Datatype]]
name = "BrakePressure"
id = 0x15

[[Datatype]]
name = "HighVoltage"
id = 0x16

[[Datatype]]
name = "HighVoltageInsulation"
id = 0x17

[[Datatype]]
name = "FSMState"
id = 0x18

[[Datatype]]
name = "FSMEvent"
id = 0x19

[[Datatype]]
name = "PodDropTriggered"
id = 0x1a

[[Datatype]]
name = "Localisation"
id = 0x1b

[[Datatype]]
name = "GFDIsolation"
id = 0x38

[[Datatype]]
name = "DefaultBMSLow"
id = 0x19C
[[Datatype]]
name = "DiagonosticBMSLow"
id = 0x1A7
[[Datatype]]
name = "DefaultBMSHigh"
id = 0x3FF
[[Datatype]]
name = "DiagonosticBMSHigh"
id = 0x408
[[Datatype]]
name = "UnknownCanId"
id = 0x7F0

[[Datatype]]
name = "Info"
id = 0x7FA

