[[Event]]
name = "DefaultEvent"
id = 0x02
priority = 0

[[Event]]
name = "Heartbeating"
id = 0x420
priority = 1

[[Event]]
name = "EmergencyBraking"
id = 0xaB
priority = 10


# ####################
# FSM Internal events.

[[Event]]
name = "ValueOutOfBounds"
id = 0x7ff
priority = 1

[[Event]]
name = "EndOfTrackTriggeredEvent"
id = 0x121
priority = 0

[[Event]]
name = "BootingCompleteEvent"
id = 0xa1
priority = 0

[[Event]]
name = "BootingFailedEvent"
id = 0xa2
priority = 0

[[Event]]
name = "ConnectionEstablishedEvent"
id = 0xa3
priority = 0

[[Event]]
name = "ConnectionEstablishFailed"
id = 0xa4
priority = 0

[[Event]]
name = "ConnectionLossEvent"
id = 0xaC
priority = 1

[[Event]]
name = "LVPropulsionReadyEvent"
id = 0x3e1
priority = 0

[[Event]]
name = "LVPowertrainReadyEvent"
id = 0xaF
priority = 0

[[Event]]
name = "HVPowertrainReadyEvent"
id = 0xb3
priority = 0

# ###################################
# User commands for the run procedure

[[Event]]
name = "RunStarting"
id = 0xb9
priority = 1 

[[Event]]
name = "ContinueRunEvent"
id = 0xbd
priority = 1 

[[Event]]
name = "SystemResetCommand"
id = 0xbE
priority = 0

[[Event]]
name = "RunConfigCompleteEvent"
id = 0xa6
priority = 0xc0

[[Event]]
name = "ExitEvent"
id = 0xc1
priority = 0

[[Event]]
name = "ArmBrakesCommand"
id = 0xb0
priority = 0

[[Event]]
name = "TurnOnHVCommand"
id = 0xb1
priority = 0

[[Event]]
name = "TurnOffHVCommand"
id = 0xb2
priority = 0

[[Event]]
id = 0x427
name = "ReConfigureCommand"
priority = 0 

[[Event]]
id = 0x429
name = "DcTurnedOn"
priority = 1 

[[Event]]
id = 0x42a
name = "DcTurnedOff"
priority = 1 

# ###########################################
# Events that carry configuration information

[[Event]]
id = 0x422
name = "SettingSpeeds"
priority = 0
params = "u64"

[[Event]]
name = "SettingRoute"
id = 0xa5
priority = 0
params = "u64"

[[Event]]
name = "SettingOverrides"
id = 0x426
priority = 0
params = "u64"

# ###########################################
# Events triggered by the Localisation system

[[Event]]
name = "LaneSwitchForward"
id = 0x502
priority = 0

[[Event]]
name = "LaneSwitchBackwardsB"
id = 0x503
priority = 0

[[Event]]
name = "LaneSwitchBackwardsC"
id = 0x504
priority = 0

[[Event]]
name = "LaneSwitchEnded"
id = 0x505
priority = 0

# [[Event]]
# name = "LaneSwitchEndedC"
# id = 0x507
# priority = 0

[[Event]]
name = "EndOfTrackReached"
id = 0xc0
priority = 5

[[Event]]
name = "BrakingPointReachedA"
id = 0x509
priority = 0

[[Event]]
name = "BrakingPointReachedB"
id = 0x510
priority = 0

[[Event]]
name = "BrakingPointReachedC"
id = 0x511
priority = 0

[[Event]]
name = "LaneSwitchingPointReachedEvent"
id = 0xbA
priority = 0

[[Event]]
name = "LaneSwitchingCompleteEvent"
id = 0xbB
priority = 0

[[Event]]
name = "DirectionChangedEvent"
id = 0xbC
priority = 0

# #######################
# Other Sensor Hub events

[[Event]]
name = "PodDropSwitchTriggered"
id = 0xbF
priority = 5

# ########################################
# Events triggered by Levitation subsystem

[[Event]]
id = 0x423
name = "LeviLaunchingEvent"
priority = 0 

[[Event]]
id = 0x424
name = "LeviLandingEvent"
priority = 0 

# #####################################################
# Status-related events triggered by the ground station

[[Event]]
name = "LVLevitationReadyEvent"
id = 0xaD
priority = 0

# ####################
# Generic error events

[[Event]]
name = "LevitationErrorEvent"
id = 0xa8
priority = 4

[[Event]]
name = "PropulsionErrorEvent"
id = 0xa9
priority = 3

[[Event]]
name = "PowertrainErrorEvent"
id = 0xaA
priority = 2

# #############################################
# Debug events.
# usually triggered by the `EmitEvent` command,
# NOT TO BE USED IN DEMONSTRATION


[[Event]]
id = 666
name = "PreventBrakingComm"
priority = 1

[[Event]]
id = 667
name = "EnableBrakingComm"
priority = 1

[[Event]]
id = 0x428
name = "SetCurrentSpeedCommand"
priority = 0 
params = "u64"

[[Event]]
name = "EnablePropulsionCommand"
id = 0x3e2
priority = 0

[[Event]]
name = "DisablePropulsionCommand"
id = 0x3e3
priority = 1

# [[Event]]
# name = "Crying"
# id = 1281
# priority = 8 
#

[[Event]]
name = "FinishPrecharge"
id = 1000
priority = 2

[[Event]]
name = "HvLevitationBelowBms"
id = 1001
priority = 1 

[[Event]]
name = "HvLevitationAboveBms"
id = 1002
priority = 1 

[[Event]]
name = "CygnusesVaryingVoltages"
id = 1003
priority = 1 

[[Event]]
name = "PrechargeAbort"
id = 1004
priority = 1 

[[Event]]
name = "LeviLedOn"
id = 1005
priority = 0

[[Event]]
name = "LeviLedOff"
id = 1006
priority = 0

[[Event]]
name = "LeviConnected"
id = 1007
priority = 1 

