[[Event]]
name = "DefaultEvent"
id = 0x02
priority = 0

[[Event]]
name = "BootingCompleteEvent"
id = 0xa1
priority = 0

[[Event]]
name = "BootingFailedEvent"
id = 0xa2
priority = 0

[[Event]]
name = "ConnectionEstablishedEvent"
id = 0xa3
priority = 0

[[Event]]
name = "ConnectionEstablishmentFailedEvent"
id = 0xa4
priority = 0

[[Event]]
name = "SetRunConfig"
id = 0xa5
priority = 0
params = "u64"

[[Event]]
name = "RunConfigCompleteEvent"
id = 0xa6
priority = 0

[[Event]]
name = "RunConfigFailedEvent"
id = 0xa7
priority = 0

[[Event]]
name = "LevitationErrorEvent"
id = 0xa8
priority = 4

[[Event]]
name = "PropulsionErrorEvent"
id = 0xa9
priority = 3

[[Event]]
name = "PowertrainErrorEvent"
id = 0xaA
priority = 2

[[Event]]
name = "EmergencyBrakeCommand"
id = 0xaB
priority = 10

[[Event]]
name = "ConnectionLossEvent"
id = 0xaC
priority = 1

[[Event]]
name = "LVLevitationReadyEvent"
id = 0xaD
priority = 0

[[Event]]
name = "LVPropulsionReadyEvent"
id = 0xaE
priority = 0

[[Event]]
name = "LVPowertrainReadyEvent"
id = 0xaF
priority = 0

[[Event]]
name = "ArmBrakesCommand"
id = 0xb0
priority = 0

[[Event]]
name = "TurnOnHVCommand"
id = 0xb1
priority = 0

[[Event]]
name = "HVPowertrainReadyEvent"
id = 0xb2
priority = 0

[[Event]]
name = "HVLevitationReadyEvent"
id = 0xb3
priority = 0

[[Event]]
name = "StartLevitatingCommand"
id = 0xb4
priority = 0

[[Event]]
name = "HVPropulsionReadyEvent"
id = 0xb5
priority = 0

[[Event]]
name = "StartAcceleratingCommand"
id = 0xb6
priority = 0

[[Event]]
name = "DesiredSpeedReachedEvent"
id = 0xb7
priority = 0

[[Event]]
name = "BrakingPointReachedEvent"
id = 0xb8
priority = 0

[[Event]]
name = "LaneSwitchingPointReachedEvent"
id = 0xb9
priority = 0

[[Event]]
name = "LaneSwitchingCompleteEvent"
id = 0xbA
priority = 0

[[Event]]
name = "DirectionChangedEvent"
id = 0xbB
priority = 0

[[Event]]
name = "RunFinishedEvent"
id = 0xbC
priority = 0

[[Event]]
name = "SystemResetCommand"
id = 0xbD
priority = 0

[[Event]]
name = "PodDropSwitchTriggered"
id = 0xbE
priority = 5

[[Event]]
name = "EndOfTrackReached"
id = 0xbF
priority = 5

[[Event]]
name = "ExitEvent"
id = 0xc0
priority = 0

[[Event]]
name = "LaneSwitchForward"
id = 0x502
priority = 0

[[Event]]
name = "LaneSwitchBackwardsB"
id = 0x503
priority = 0

[[Event]]
name = "LaneSwitchBackwardsC"
id = 0x504
priority = 0
