
set MATLAB=C:\Program Files\MATLAB\R2021a

"C:\Program Files\MATLAB\R2021a\bin\win64\gmake" -f ControllerLateral.mk  PMP_TOP_LEVEL_MODEL="ControllerLateral" PMP_SAMPLEPERIOD="0.0002500000" PMP_IS_SLAVE="off" INCLUDE_MDL_TERMINATE_FCN=1 OPTS="-DRT_MALLOC -DTID01EQ=0"
