name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: rustup target add thumbv7em-none-eabihf && cd app && cargo build
    # - name: Run tests
      # run: cargo test --verbose

  station:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo echo "deb http://archive.ubuntu.com/ubuntu focal-updates main" >> /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgdk-3-dev
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH

      # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.

    - name: setup node
      uses: actions/setup-node@v4
      with:
          node-version: lts/*
          cache-dependency-path: ./gs/
          cache: 'npm'

    - name: Build
      run: cd gs/station && cargo build --features full
    - name: Run tests
      run: cd gs/station cargo test --features full
