name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: rustup target add thumbv7em-none-eabihf && cd app && cargo build
    # - name: Run tests
      # run: cargo test --verbose

  station:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies (ubuntu only)
      if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.

    - name: Build
      run: cd gs/station && cargo build --features full
    - name: Run tests
      run: cd gs/station cargo test --features full
